modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Faster%20Crouching"
logoFile="icon.png"

[[mods]]
modId="fastercrouching"
version="2.5"
displayName="Faster Crouching"
displayURL="https://serilum.com/mod/faster-crouching"
authors="Rick South"
description='''Set the crouch/sneak speed of players to be the same as when walking and sprinting.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.fastercrouching]]
    modId="collective"
    type="required"
    versionRange="[7.53,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fastercrouching]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.5]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "fastercrouching.mixins.json"